# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/constrs/pin.xdc

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/constrs/misc.xdc

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/constrs/timing.xdc

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/constrs/debug.xdc

# Block Designs: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_dpu_clk_wiz_0/top_dpu_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dpu_clk_wiz_0 || ORIG_REF_NAME==top_dpu_clk_wiz_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_clk_0/top_rst_gen_clk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_gen_clk_0 || ORIG_REF_NAME==top_rst_gen_clk_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_clk_dsp_0/top_rst_gen_clk_dsp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_gen_clk_dsp_0 || ORIG_REF_NAME==top_rst_gen_clk_dsp_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_dpu_intc_M_AXI_LPD_0/top_dpu_intc_M_AXI_LPD_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dpu_intc_M_AXI_LPD_0 || ORIG_REF_NAME==top_dpu_intc_M_AXI_LPD_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_dpu_intc_M_AXI_HP0_FPD_0/top_dpu_intc_M_AXI_HP0_FPD_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dpu_intc_M_AXI_HP0_FPD_0 || ORIG_REF_NAME==top_dpu_intc_M_AXI_HP0_FPD_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_dpu_intc_M_AXI_HP1_FPD_0/top_dpu_intc_M_AXI_HP1_FPD_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dpu_intc_M_AXI_HP1_FPD_0 || ORIG_REF_NAME==top_dpu_intc_M_AXI_HP1_FPD_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_dpu_concat_irq_inner_0/top_dpu_concat_irq_inner_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dpu_concat_irq_inner_0 || ORIG_REF_NAME==top_dpu_concat_irq_inner_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_DPUCZDX8G_0/top_DPUCZDX8G_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_DPUCZDX8G_0 || ORIG_REF_NAME==top_DPUCZDX8G_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_zynq_ultra_ps_e_0/top_zynq_ultra_ps_e_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_zynq_ultra_ps_e_0 || ORIG_REF_NAME==top_zynq_ultra_ps_e_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_dpu_concat_irq_0/top_dpu_concat_irq_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dpu_concat_irq_0 || ORIG_REF_NAME==top_dpu_concat_irq_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_reg_0/top_rst_gen_reg_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_gen_reg_0 || ORIG_REF_NAME==top_rst_gen_reg_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_ghp_0/top_rst_gen_ghp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_gen_ghp_0 || ORIG_REF_NAME==top_rst_gen_ghp_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_auto_cc_0/top_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_cc_0 || ORIG_REF_NAME==top_auto_cc_0} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_auto_cc_1/top_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_cc_1 || ORIG_REF_NAME==top_auto_cc_1} -quiet] -quiet

# IP: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_auto_cc_2/top_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_cc_2 || ORIG_REF_NAME==top_auto_cc_2} -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_dpu_clk_wiz_0/top_dpu_clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_dpu_clk_wiz_0 || ORIG_REF_NAME==top_dpu_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_dpu_clk_wiz_0/top_dpu_clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_dpu_clk_wiz_0 || ORIG_REF_NAME==top_dpu_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_dpu_clk_wiz_0/top_dpu_clk_wiz_0_ooc.xdc

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_clk_0/top_rst_gen_clk_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_gen_clk_0 || ORIG_REF_NAME==top_rst_gen_clk_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_clk_0/top_rst_gen_clk_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_gen_clk_0 || ORIG_REF_NAME==top_rst_gen_clk_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_clk_dsp_0/top_rst_gen_clk_dsp_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_gen_clk_dsp_0 || ORIG_REF_NAME==top_rst_gen_clk_dsp_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_clk_dsp_0/top_rst_gen_clk_dsp_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_gen_clk_dsp_0 || ORIG_REF_NAME==top_rst_gen_clk_dsp_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_DPUCZDX8G_0/top_DPUCZDX8G_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_DPUCZDX8G_0 || ORIG_REF_NAME==top_DPUCZDX8G_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_DPUCZDX8G_0/top_DPUCZDX8G_0_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_DPUCZDX8G_0 || ORIG_REF_NAME==top_DPUCZDX8G_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_zynq_ultra_ps_e_0/top_zynq_ultra_ps_e_0_ooc.xdc

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_zynq_ultra_ps_e_0/top_zynq_ultra_ps_e_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_zynq_ultra_ps_e_0 || ORIG_REF_NAME==top_zynq_ultra_ps_e_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_reg_0/top_rst_gen_reg_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_gen_reg_0 || ORIG_REF_NAME==top_rst_gen_reg_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_reg_0/top_rst_gen_reg_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_gen_reg_0 || ORIG_REF_NAME==top_rst_gen_reg_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_ghp_0/top_rst_gen_ghp_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_gen_ghp_0 || ORIG_REF_NAME==top_rst_gen_ghp_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_rst_gen_ghp_0/top_rst_gen_ghp_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_rst_gen_ghp_0 || ORIG_REF_NAME==top_rst_gen_ghp_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_auto_cc_0/top_auto_cc_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_auto_cc_0 || ORIG_REF_NAME==top_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_auto_cc_0/top_auto_cc_0_ooc.xdc

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_auto_cc_1/top_auto_cc_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_auto_cc_1 || ORIG_REF_NAME==top_auto_cc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_auto_cc_1/top_auto_cc_1_ooc.xdc

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_auto_cc_2/top_auto_cc_2_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_auto_cc_2 || ORIG_REF_NAME==top_auto_cc_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/ip/top_auto_cc_2/top_auto_cc_2_ooc.xdc

# XDC: /home/madhusudhan/Downloads/DPUCZDX8G_VAI_v3.0/prj/Vivado/hw/srcs/top/top_ooc.xdc
